apps/ticket/urls.py
from django.urls import path
from apps.ticket import views

app_name = 'ticket'
urlpatterns = [
    path('', views.DashboardView.as_view(), name="dashboard"),

    # Ticket
    path('ticket/create/', views.CreateNewTicket.as_view(), name="create-new-ticket"),
    path('ticket/', views.ListTicketView.as_view(), name="list-ticket"),
    path('ticket/detail/<int:pk>', views.DetailTicketView.as_view(), name="detail-ticket"),
    path('ticket/update/<int:pk>', views.UpdateTicketView.as_view(), name="update-ticket"),
    path('ticlet/delete/<int:pk>', views.DeleteTicketView.as_view(), name="delete-ticket"),

    # Checker
    path('checker/', views.ListCheckerTicketView.as_view(), name="list-checker"),
    path('checker/detail/<int:pk>', views.DetailCheckerView.as_view(), name="detail-checker"),
    path('checker/update/<int:pk>', views.UpdateCheckerView.as_view(), name="update-checker"),
    path('checker/update-info/<int:pk>', views.UpdateInfoCheckerView.as_view(), name="update-info-checker"),

    #  Inbox
    path('inbox/', views.ListInboxView.as_view(), name="list-inbox"),
    path('inbox/detail/<int:pk>', views.DetailInboxView.as_view(), name="detail-inbox"),
    path('inbox/update/<int:pk>', views.UpdateInboxStatusTicketView.as_view(), name="update-inbox-status-ticket"),

    # Tracker
    path('tracker/', views.listTrackerView.as_view(), name="list-tracker-ticket"),
    path('tracker/detail/<int:pk>', views.ListDetailTrackerView.as_view(), name="list-detail-tracker-ticket")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('dashboard/', include('apps.ticket.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/checker/detail-checker.html
{% extends 'base.html' %}
{% block title %}
    Detail ticket
{% endblock title %}

{% block content %}
    <h1>Detail ticket</h1>
    <h3>{{ checker_tickets.checker.title }}</h3>
    <p>{{ checker_tickets.checker.content }}</p>
    <img src="{{checker_tickets.checker.picture.url}}" alt="">
    <p>author: {{ checker_tickets.checker.author }}</p>

    <h4>send_to:</h4>
    <ul>
        {% for send_to in checker_tickets.checker.send_to.all %}
        <li>
            {{ send_to.username }}
        </li>
        {% endfor %}
    </ul>

    <h4>checker:</h4>
    <ul>
        {% for checker in checker_tickets.checker.checker.all %}
        <li>
            {{ checker.username }}
        </li>
        {% endfor %}
    </ul>
    <p>create: {{ checker_tickets.checker.create }}</p>
    <p>updated: {{ checker_tickets.checker.updated }}</p>
    <p>approve: {{ checker_tickets.approve }}</p>

{% endblock content %}

templates/dashboard/checker/list-checker.html
{% extends 'base.html' %}
{% block title %}
    list checker ticket
{% endblock title %}

{% block content %}
    <h1>Checker</h1>
    <h3>Checker List</h3>
    <table>
      <tr>
        <th>Ticket</th>
          <th>Approve</th>
        <th>Action</th>
      </tr>
        {% for checker_ticket in checker_tickets %}
      <tr>
        <td><a href="{% url 'ticket:detail-checker'  checker_ticket.pk %}">{{ checker_ticket.checker.title }}</a></td>
          <td><a href="{% url 'ticket:update-checker' checker_ticket.pk %}">{{ checker_ticket.approve }}</a></td>
        <td><a href="{% url 'ticket:update-ticket' checker_ticket.checker.pk %}">update</a>&nbsp;&nbsp;<a href="{% url 'ticket:update-info-checker' checker_ticket.checker.pk %}">info</a></td>
      </tr>
    {% endfor %}
    </table>

    <br><br>
    <a href="/dashboard/">back</a>

{% endblock content %}

templates/dashboard/checker/update-info-checker.html
{% extends 'base.html' %}
{% block title %}
    Update Ticket
{% endblock title %}

{% block content %}
    <h1>Update Ticket</h1>
    <h3>{{ title }}</h3>
    <p>info: {{ info }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="info">info:</label><br>
        <input type="text" id="info" name="info"><br><br>
        <button type="submit">save</button>
    </form>
{% endblock content %}