apps/ticket/urls.py
from django.urls import path
from apps.ticket import views

app_name = 'ticket'
urlpatterns = [
    path('', views.DashboardView.as_view(), name="dashboard"),

    # Ticket
    path('ticket/create/', views.CreateNewTicket.as_view(), name="create-new-ticket"),
    path('ticket/', views.ListTicketView.as_view(), name="list-ticket"),
    path('ticket/detail/<int:pk>', views.DetailTicketView.as_view(), name="detail-ticket"),
    path('ticket/update/<int:pk>', views.UpdateTicketView.as_view(), name="update-ticket"),
    path('ticlet/delete/<int:pk>', views.DeleteTicketView.as_view(), name="delete-ticket"),

    # Checker
    path('checker/', views.ListCheckerTicketView.as_view(), name="list-checker"),
    path('checker/detail/<int:pk>', views.DetailCheckerView.as_view(), name="detail-checker"),
    path('checker/update/<int:pk>', views.UpdateCheckerView.as_view(), name="update-checker"),
    path('checker/update-info/<int:pk>', views.UpdateInfoCheckerView.as_view(), name="update-info-checker"),

    #  Inbox
    path('inbox/', views.ListInboxView.as_view(), name="list-inbox"),
    path('inbox/detail/<int:pk>', views.DetailInboxView.as_view(), name="detail-inbox"),
    path('inbox/update/<int:pk>', views.UpdateInboxStatusTicketView.as_view(), name="update-inbox-status-ticket"),

    # Tracker
    path('tracker/', views.listTrackerView.as_view(), name="list-tracker-ticket"),
    path('tracker/detail/<int:pk>', views.ListDetailTrackerView.as_view(), name="list-detail-tracker-ticket")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('dashboard/', include('apps.ticket.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/inbox/detail-inbox.html
{% extends 'base.html' %}
{% block title %}
    Detail ticket inbox
{% endblock title %}

{% block content %}
    <h1>Detail ticket inbox</h1>
    <h3>{{ inbox.checker.title }}</h3>
    <p>{{ inbox.checker.content }}</p>
    <img src="{{inbox.checker.picture.url}}" alt="">
    <p>author: {{ inbox.checker.author }}</p>
{% endblock content %}

templates/dashboard/inbox/list-inbox.html
{% extends 'base.html' %}
{% block title %}
    Inbox Tickets
{% endblock title %}

{% block content %}
    <h1>Inbox</h1>
    <table>
      <tr>
        <th>Ticket</th>
        <th>Status</th>
      </tr>
        {% for ticket in data_tickets %}
      <tr>
        <td><a href="{% url 'ticket:detail-inbox' ticket.pk %}">{{ ticket.checker.title }}</a></td>
          <td><a href="{% url 'ticket:update-inbox-status-ticket' ticket.checker.id %}">{{ ticket.checker.status_ticket }}</a></td>
      </tr>
    {% endfor %}
    </table>

    <br><br>
    <a href="/dashboard/">back</a>

{% endblock content %}